#!/bin/sh
VER=$1

wget http://www.bro.org/downloads/release/bro-${VER}.tar.gz
tar xvzf bro-${VER}.tar.gz
cd bro-${VER}
./configure --prefix=/bro-${VER} && make && make install
rm bro-${VER}.tar.gz
rm -rf bro-${VER}
