#!/bin/sh
VER=$1

cd /tmp/bro
git pull
git checkout $VER
git reset --hard
git submodule foreach --recursive git reset --hard
git checkout .
git submodule foreach --recursive git checkout .
./configure --prefix=/bro-master && make && make install
rm -rf /tmp/bro
