#!/bin/sh
export BRO_DNS_FAKE=1

cd /brostuff/*/ || exit 1
opts=""

if [ -e file.pcap ]; then
    opts="-r file.pcap"
fi


/usr/bin/timeout -k 2 30 /bro/bin/bro -C $opts ./main.bro > stdout.log 2> stderr.log

#remove harmless message
grep -v 'problem initializing NB-DNS' stderr.log > tmp.log
mv tmp.log stderr.log
