#!/bin/sh

export BRO_DNS_FAKE=1

PROG=/bro/bin/bro
if [ -x /zeek/bin/zeek ] ; then
    PROG=/zeek/bin/zeek
fi

cd /brostuff/*/ || exit 1
opts=""

if [ -e file.pcap ]; then
    opts="-r file.pcap"
fi


chown nobody . *
mv main.bro trybro.bro
cat <<EOF > __pre.bro
redef Site::local_nets += { 0.0.0.0/0 };
@ifndef(zeek_init)
global zeek_init: event();
global zeek_done: event();
event bro_init() { event zeek_init() ; }
event bro_done() { event zeek_done() ; }
@endif
EOF
su -s /bin/sh nobody -c "/usr/bin/timeout -k 2 15 $PROG -C $opts local  __pre.bro ./trybro.bro > stdout.log 2> stderr.log"

#remove harmless message
grep -v 'NB-DNS' stderr.log | grep -v 'issue DNS request' > tmp.log
mv tmp.log stderr.log

#remove useless output files
rm -f loaded_scripts.log packet_filter.log notice_policy.log
