#!/bin/sh

export ZEEK_DNS_FAKE=1
export BRO_DNS_FAKE=1

for prog in /bro/bin/bro /bro/bin/zeek /usr/local/zeek/bin/zeek ; do
    if [ -x $prog ] ; then
        PROG=$prog
    fi
done

cd /brostuff/*/ || exit 1
opts=""

if [ -e file.pcap ]; then
    opts="-r file.pcap"
fi


chown nobody . ./*
#Try both, just in case
mv main.zeek try.zeek || mv main.bro try.zeek

cat <<EOF > __pre.zeek
redef Site::local_nets += { 0.0.0.0/0 };
@ifndef(zeek_init)
global zeek_init: event();
global zeek_done: event();
event bro_init() { event zeek_init() ; }
event bro_done() { event zeek_done() ; }
@endif
EOF
su -s /bin/sh nobody -c "/usr/bin/timeout -k 2 15 $PROG -C $opts local  __pre.zeek ./try.zeek > stdout.log 2> stderr.log"

#remove harmless message
grep -v 'NB-DNS' stderr.log | grep -v 'issue DNS request' > tmp.log
mv tmp.log stderr.log

#remove useless output files
rm -f loaded_scripts.log packet_filter.log notice_policy.log
